name: brunops.org
description: Bruno Sanches personal website with projects, notes and thoughts

markdown: redcarpet
pygments: true
permalink: /:title
paginate: 5
paginate_path: /page-:num

url: http://brunops.org
